export enum todosConstants {
  NEW = 'NEW_TODO',
  EDIT = 'EDIT_TODO',

  FILTER = 'FILTER',
  FILTER_BY_TAG = 'FILTER_BY_TAG',

  UPCOMING_FILTER = 'UPCOMING',
  TODAY_FILTER = 'TODAY',
  INBOX_FILTER = 'INBOX',
  COMPLETED_FILTER = 'COMPLETED'
}
